import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity/visual-editing";
import { Params } from "next/dist/server/request/params";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  ...props
}: Readonly<{
  children: React.ReactNode;
  params: Promise<Params>;
}>) {
  const params = await props.params;
  const lang = params.lang ?? "sv";
  return (
    <html lang={lang as string}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        {(await draftMode()).isEnabled && <VisualEditing />}
      </body>
    </html>
  );
}
